# Generated by Django 5.1.4 on 2024-12-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Page",
        ),
    ]
