# Generated by Django 5.1.4 on 2024-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp",
            field=models.CharField(default="ab4df7", max_length=6),
        ),
    ]
